### ISSUE TITLE
Feature Request: Option to disable the items

### ISSUE THREAD

**Issue by sternschnaube** [Tschipcraft/more_mobs#1]
### Is your suggested enhancement related to a problem? Please describe.

I really love this mod - however, I would like to stick more to vanilla.
A option to disable entirely the spawned items with them (Potion of Dragon Breath, Damaged Elytra, Totem of Undying, etc) would be great.

Armor, Swords, Bow, Crossbow and Trident is fine.
I'm just here for the heads - fancy particle effects and buffs are fine 😊

**Comment by Tschipcraft** [comment]
Thanks <3
This should be an easy addition. At least the Totem of Undying will never drop since the mob uses it before dying.

**Comment by Tschipcraft** [comment]
I've now implemented the option. I plan on adding some more stuff until I release the next version, so if you want to play with it now, download the repository directly and extract _more_mobs-master_.

**Comment by sternschnaube** [comment]
Thank you so much 😊
