### ISSUE TITLE
No Mobs spawning

### ISSUE THREAD

**Issue by Broncosito** [Tschipcraft/more_mobs#10]
No mob spawning 

Hello, only some creeper and endermen are spawning after installing the datapack on our multiplayer server. Via Spawner there are mobs spawning though. What can we do? We got only one custom shop plugin on the server.

**Comment by Tschipcraft** [comment]
Thank you for the bug report, do the mobs themselves not spawn or the custom mobs?

**Comment by Broncosito** [comment]
Only normal creepers and endermen spawn, sometimes. I stood for like 1h in a deep down cave and nothing spawned. All non hostile mobs do spawn though.

**Comment by Tschipcraft** [comment]
That's weird... More Mobs does not change spawning rates in any way, but only modifies already spawned mobs by random chance, so it's most likely a misconfiguration of the multiplayer server. Does the problem disappear when removing More Mobs?

**Comment by Broncosito** [comment]
yes, when we removed it, it worked totally fine

**Comment by Broncosito** [comment]
will do it when the owner is back in a few days

**Comment by Tschipcraft** [comment]
@Broncosito, any updates on this?

**Comment by Broncosito** [comment]
didnt hear anything from the owner. i guess we can close this thread :/

**Comment by Tschipcraft** [comment]
Alright, if you happen to get more information or anyone else having this issue, feel free to reopen this thread.
