### ISSUE TITLE
Add 1.20.6/1.21 support

### ISSUE THREAD

**Issue by wykwey** [Tschipcraft/more_mobs#12]
### Is your suggested enhancement related to a problem? Please describe.

Can you add support for 1.20.6?

**Comment by Tschipcraft** [comment]
I will start working on the update in approx. 2 weeks after my exams. Thanks for your patience!

**Comment by sternschnaube** [comment]
Thank you @Tschipcraft 😄 
I hope 1.21 support as well.

**Comment by sternschnaube** [comment]
Thanks for the update ☺️
