### ISSUE TITLE
skeletons no longer spawn with bows

### ISSUE THREAD

**Issue by binc404** [Tschipcraft/more_mobs#16]
### Describe the bug

skeletons dont spawn with bows or swords or anything. they dont have anything. always just a random head but nothing more.
only while using spawn animations datapack

**Comment by Tschipcraft** [comment]
Which Minecraft version are you using?

**Comment by binc404** [comment]
1.20.6 on a server

**Comment by Tschipcraft** [comment]
Are you using the dev version of Spawn Animations (compiled from this pull request https://github.com/Tschipcraft/spawnanimations/pull/28) or the latest release? (the latest release is not compatible with Minecraft 1.20.6 yet)

**Comment by Tschipcraft** [comment]
Spawn Animations v1.10 has support for 1.20.6, this should no longer be an issue
