### ISSUE TITLE
Mobs with heads wont burn

### ISSUE THREAD

**Issue by R0gyman** [Tschipcraft/more_mobs#3]
### Is your feature request related to a problem? Please describe.

All mobs with head pieces need to burn in the sunlight. in regular minecraft helmets will break off slowly i sudgest it act like they dont have anything equipped at all.

**Comment by Tschipcraft** [comment]
To implement this, I would have to implement a (for versions prior to Minecraft 1.19.4) very complicated sky and rain check and set the mobs on fire manually.
But it could maybe be added as an exclusive feature for Minecraft 1.19.4 and up.

**Comment by Tschipcraft** [comment]
Implemented as of 6a472cf!
