### ISSUE TITLE
mobs don't die in the sun

### ISSUE THREAD

**Issue by SMCarvalho** [Tschipcraft/more_mobs#4]
### Describe the bug

mobs that have a custom head don't die when it's daytime.

### Expected behavior

let the mobs die

### Additional context

![2023-07-08_13 26 22](https://github.com/Tschipcraft/more_mobs/assets/139001097/ba3a7855-90a7-48b3-9313-1fb0333bf504)

**Comment by Tschipcraft** [comment]
Duplicate of #3
